name: SwiftOBD2App
options:
  bundleIdPrefix: com.myapp
targets:
  SMARTOBD2:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    dependencies:
      - package:
            url: "https://github.com/kkonteh97/SwiftOBD2.git"
    info:
      path: "SwiftOBD2App/Info.plist"
      properties:
        CFBundleDisplayName: $(PRODUCT_NAME)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        UILaunchStoryboardName: "LaunchScreen"
        NSBluetoothAlwaysUsageDescription: "This app uses Bluetooth to connect to nearby devices."
        NSBluetoothPeripheralUsageDescription: "This app uses Bluetooth to connect to nearby devices."
        NSLocationAlwaysUsageDescription: "This app uses location services to connect to nearby devices."
        NSLocationWhenInUseUsageDescription: "This app uses location services to connect to nearby devices."
        UIBackgroundModes: ["bluetooth-central"]
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    sources:
      - path: "SwiftOBD2App"

